import Stripe from "stripe";
import Transaction from "../models/Transaction.js";

const stripe = process.env.STRIPE_SECRET_KEY ? new Stripe(process.env.STRIPE_SECRET_KEY) : null;

/**
 * Deposit intents: called once both parties have agreed to a contract's terms.
 * Card is wired to Stripe PaymentIntents for the full contract total. Bank and crypto
 * are stubbed - swap in a licensed banking-as-a-service provider (Wise, Flutterwave,
 * Plaid+bank rails) and a regulated custodian (Fireblocks, BitGo, Circle) respectively.
 */
export async function createDepositIntent(escrow) {
  const total = escrow.totalAmount ?? escrow.milestones.reduce((s, m) => s + m.amount, 0);

  if (escrow.fundingMethod === "card") {
    if (!stripe) {
      console.warn("[legion] STRIPE_SECRET_KEY not configured - skipping real card intent");
      return null;
    }
    const intent = await stripe.paymentIntents.create({
      amount: Math.round(total * 100),
      currency: escrow.currency.toLowerCase(),
      metadata: { legionId: escrow.legionId },
      capture_method: "manual", // hold funds; capture per milestone as each one releases
    });
    await Transaction.create({
      escrow: escrow._id, type: "deposit", method: "card", amount: total,
      currency: escrow.currency, provider: "stripe", providerRef: intent.id, status: "pending",
    });
    return { clientSecret: intent.client_secret };
  }

  if (escrow.fundingMethod === "bank") {
    // TODO: call your bank/payment provider to generate a virtual account or payment reference.
    await Transaction.create({
      escrow: escrow._id, type: "deposit", method: "bank", amount: total,
      currency: escrow.currency, provider: "bank_provider_stub", status: "pending",
    });
    return { reference: `LEGION-${escrow.legionId}`, instructions: "Bank transfer instructions would be generated by your provider here." };
  }

  if (escrow.fundingMethod === "crypto") {
    // TODO: call your crypto custody/settlement provider to generate a deposit address.
    await Transaction.create({
      escrow: escrow._id, type: "deposit", method: "crypto", amount: total,
      currency: escrow.currency, provider: "crypto_provider_stub", status: "pending",
    });
    return { depositAddress: "stub-address-from-your-custody-provider" };
  }
}

/**
 * Payout for a single milestone on release. Fee for that milestone is taken
 * proportionally from the contract's overall agentFeeAmount.
 */
export async function createPayout(escrow, milestone) {
  const total = escrow.totalAmount ?? escrow.milestones.reduce((s, m) => s + m.amount, 0);
  const milestoneFee = total > 0 ? (milestone.amount / total) * escrow.agentFeeAmount : 0;

  if (escrow.payoutMethod === "card" && stripe) {
    // In production: capture the relevant portion of the held PaymentIntent,
    // or push out via Stripe Connect/Treasury payouts.
    console.log(`[legion] (stub) would capture/payout ${milestone.amount} ${escrow.currency} for ${escrow.legionId} / milestone ${milestone._id}`);
  }

  await Transaction.create({
    escrow: escrow._id, type: "payout", method: escrow.payoutMethod, amount: milestone.amount,
    currency: escrow.currency, provider: `${escrow.payoutMethod}_provider_stub`, status: "pending",
  });
  await Transaction.create({
    escrow: escrow._id, type: "fee", method: escrow.payoutMethod, amount: Math.round(milestoneFee * 100) / 100,
    currency: escrow.currency, provider: "legion_internal", status: "completed",
  });
}

// POST /api/payments/stripe/webhook - card deposit/capture confirmations
export async function stripeWebhook(req, res) {
  if (!stripe) return res.status(400).json({ error: "Stripe not configured" });
  let event;
  try {
    event = stripe.webhooks.constructEvent(req.body, req.headers["stripe-signature"], process.env.STRIPE_WEBHOOK_SECRET);
  } catch (err) {
    return res.status(400).send(`Webhook signature verification failed: ${err.message}`);
  }

  if (event.type === "payment_intent.succeeded" || event.type === "payment_intent.amount_capturable_updated") {
    const intent = event.data.object;
    await Transaction.findOneAndUpdate({ providerRef: intent.id }, { status: "completed" });
    // TODO: also mark the related Escrow.status = "active" and fundedAt = now
  }

  res.json({ received: true });
}

// POST /api/payments/bank/webhook - bank provider confirms an incoming transfer
export async function bankWebhook(req, res) {
  // TODO: verify the provider's signature, match the reference to a Transaction, mark it completed.
  res.json({ received: true });
}

// POST /api/payments/crypto/webhook - custody provider confirms on-chain deposit
export async function cryptoWebhook(req, res) {
  // TODO: verify the provider's signature, confirm required confirmations, mark completed.
  res.json({ received: true });
}
