import Stripe from "stripe";
import Transaction from "../models/Transaction.js";
import Escrow from "../models/Escrow.js";

const stripe = process.env.STRIPE_SECRET_KEY ? new Stripe(process.env.STRIPE_SECRET_KEY) : null;

function bankReference(escrow) {
  return `LEGION-${escrow.legionId}`;
}

/**
 * Deposit intents: called once both parties have agreed to a contract's terms.
 * Card is wired to Stripe PaymentIntents for the full contract total. Bank and crypto
 * are stubbed - swap in a licensed banking-as-a-service provider (Wise, Flutterwave,
 * Plaid+bank rails) and a regulated custodian (Fireblocks, BitGo, Circle) respectively.
 */
export async function createDepositIntent(escrow) {
  const total = escrow.totalAmount ?? escrow.milestones.reduce((s, m) => s + m.amount, 0);

  if (escrow.fundingMethod === "card") {
    if (!stripe) {
      console.warn("[legion] STRIPE_SECRET_KEY not configured - skipping real card intent");
      return null;
    }
    const intent = await stripe.paymentIntents.create({
      amount: Math.round(total * 100),
      currency: escrow.currency.toLowerCase(),
      metadata: { legionId: escrow.legionId },
      capture_method: "manual",
    });
    await Transaction.create({
      escrow: escrow._id, type: "deposit", method: "card", amount: total,
      currency: escrow.currency, provider: "stripe", providerRef: intent.id, status: "pending",
    });
    return { clientSecret: intent.client_secret };
  }

  if (escrow.fundingMethod === "bank") {
    await Transaction.create({
      escrow: escrow._id, type: "deposit", method: "bank", amount: total,
      currency: escrow.currency, provider: "bank_provider_stub", providerRef: bankReference(escrow), status: "pending",
    });
    return { reference: bankReference(escrow), instructions: "Bank transfer instructions would be generated by your provider here." };
  }

  if (escrow.fundingMethod === "crypto") {
    await Transaction.create({
      escrow: escrow._id, type: "deposit", method: "crypto", amount: total,
      currency: escrow.currency, provider: "crypto_provider_stub", providerRef: bankReference(escrow), status: "pending",
    });
    return { depositAddress: "stub-address-from-your-custody-provider", reference: bankReference(escrow) };
  }
}

/**
 * Payout for a single milestone on normal release. Fee for that milestone is taken
 * proportionally from the contract's overall agentFeeAmount.
 */
export async function createPayout(escrow, milestone) {
  const total = escrow.totalAmount ?? escrow.milestones.reduce((s, m) => s + m.amount, 0);
  const milestoneFee = total > 0 ? (milestone.amount / total) * escrow.agentFeeAmount : 0;

  if (escrow.payoutMethod === "card" && stripe) {
    console.log(`[legion] (stub) would capture/payout ${milestone.amount} ${escrow.currency} for ${escrow.legionId} / milestone ${milestone._id}`);
  }

  await Transaction.create({
    escrow: escrow._id, type: "payout", method: escrow.payoutMethod, amount: milestone.amount,
    currency: escrow.currency, provider: `${escrow.payoutMethod}_provider_stub`, status: "pending",
  });
  await Transaction.create({
    escrow: escrow._id, type: "fee", method: escrow.payoutMethod, amount: Math.round(milestoneFee * 100) / 100,
    currency: escrow.currency, provider: "legion_internal", status: "completed",
  });
}

/**
 * Full refund of a single milestone back to the depositor - used when a dispute
 * resolves in the depositor's favor. No agent fee is charged on a refunded
 * milestone, since the contracted work was never actually delivered.
 */
export async function createRefund(escrow, milestone) {
  await Transaction.create({
    escrow: escrow._id, type: "refund", method: escrow.fundingMethod, amount: milestone.amount,
    currency: escrow.currency, provider: `${escrow.fundingMethod}_provider_stub`, status: "pending",
  });
}

/**
 * Used when an agent resolves a dispute as a "split": divides one milestone's
 * amount between a beneficiary payout and a depositor refund according to
 * `beneficiaryPercent` (0-100). Both legs are recorded as separate transactions
 * so the audit trail shows exactly how the funds were divided. No fee is charged
 * on the depositor's refunded portion; a proportional fee applies to the
 * beneficiary's portion only.
 */
export async function createSplitPayout(escrow, milestone, beneficiaryPercent) {
  const beneficiaryAmount = Math.round(milestone.amount * (beneficiaryPercent / 100) * 100) / 100;
  const depositorAmount = Math.round((milestone.amount - beneficiaryAmount) * 100) / 100;
  const total = escrow.totalAmount ?? escrow.milestones.reduce((s, m) => s + m.amount, 0);
  const milestoneFee = total > 0 ? (milestone.amount / total) * escrow.agentFeeAmount : 0;
  const beneficiaryFee = beneficiaryPercent > 0 ? milestoneFee * (beneficiaryPercent / 100) : 0;

  if (beneficiaryAmount > 0) {
    await Transaction.create({
      escrow: escrow._id, type: "payout", method: escrow.payoutMethod, amount: beneficiaryAmount,
      currency: escrow.currency, provider: `${escrow.payoutMethod}_provider_stub`, status: "pending",
    });
    await Transaction.create({
      escrow: escrow._id, type: "fee", method: escrow.payoutMethod, amount: Math.round(beneficiaryFee * 100) / 100,
      currency: escrow.currency, provider: "legion_internal", status: "completed",
    });
  }
  if (depositorAmount > 0) {
    await Transaction.create({
      escrow: escrow._id, type: "refund", method: escrow.fundingMethod, amount: depositorAmount,
      currency: escrow.currency, provider: `${escrow.fundingMethod}_provider_stub`, status: "pending",
    });
  }
  return { beneficiaryAmount, depositorAmount };
}

/**
 * Shared by all three deposit webhook handlers: marks the matching Transaction as
 * completed and, the first time this happens for a contract, flips the Escrow into
 * a funded, active state. Idempotent - safe to call more than once for the same
 * transaction (e.g. a retried webhook).
 */
async function markDepositFunded(transaction) {
  if (!transaction || transaction.type !== "deposit") return;
  if (transaction.status !== "completed") {
    transaction.status = "completed";
    await transaction.save();
  }

  const escrow = await Escrow.findById(transaction.escrow);
  if (!escrow) return;
  if (!escrow.fundedAt) {
    escrow.fundedAt = new Date();
  }
  if (escrow.status === "pending_agreement" || escrow.status === "active") {
    escrow.status = "active";
  }
  await escrow.save();
}

// POST /api/payments/stripe/webhook
export async function stripeWebhook(req, res) {
  if (!stripe) return res.status(400).json({ error: "Stripe not configured" });
  let event;
  try {
    event = stripe.webhooks.constructEvent(req.body, req.headers["stripe-signature"], process.env.STRIPE_WEBHOOK_SECRET);
  } catch (err) {
    return res.status(400).send(`Webhook signature verification failed: ${err.message}`);
  }

  if (event.type === "payment_intent.succeeded" || event.type === "payment_intent.amount_capturable_updated") {
    const intent = event.data.object;
    const transaction = await Transaction.findOne({ providerRef: intent.id });
    await markDepositFunded(transaction);
  }

  res.json({ received: true });
}

// POST /api/payments/bank/webhook
// { reference: "LEGION-88213", status: "completed" }
export async function bankWebhook(req, res) {
  const { reference, status } = req.body;
  if (!reference || status !== "completed") return res.json({ received: true });

  const transaction = await Transaction.findOne({ providerRef: reference, method: "bank", type: "deposit" });
  await markDepositFunded(transaction);
  res.json({ received: true });
}

// POST /api/payments/crypto/webhook
// { reference: "LEGION-88213", confirmations: 6, requiredConfirmations: 6 }
export async function cryptoWebhook(req, res) {
  const { reference, confirmations, requiredConfirmations } = req.body;
  if (!reference || (confirmations ?? 0) < (requiredConfirmations ?? 1)) return res.json({ received: true });

  const transaction = await Transaction.findOne({ providerRef: reference, method: "crypto", type: "deposit" });
  await markDepositFunded(transaction);
  res.json({ received: true });
}